const C={cp:'#80dfff',up:'#e070c0',dn:'#afd485',alert:'#ff4d4d'};let charts={};
function fmt(n){return Number(n).toLocaleString('en-US',{maximumFractionDigits:2})}
function rating(v){return v>=75?'극탐욕 (Extreme Greed)':v>=55?'탐욕 (Greed)':v>=45?'중립 (Neutral)':v>=25?'공포 (Fear)':'극공포 (Extreme Fear)'}
function makeChart(id,labels,price,up,dn){charts[id]?.destroy();charts[id]=new Chart(document.getElementById(id),{type:'line',data:{labels,datasets:[{label:'Price',data:price,borderColor:C.cp,borderWidth:2,pointRadius:0,spanGaps:true},{label:'Upper',data:up,borderColor:C.up,borderWidth:1.5,pointRadius:0,spanGaps:true},{label:'Lower',data:dn,borderColor:C.dn,borderWidth:1.5,pointRadius:0,spanGaps:true}]},options:{responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{display:false},tooltip:{mode:'index',intersect:false}},interaction:{mode:'index',intersect:false},scales:{x:{display:false},y:{ticks:{color:'#aaa'},grid:{color:'#222'},border:{display:false}}}}})}
function renderSignal(el,s){const below=s.pos==='BELOW';let name,lines;if(below){name='하단 밴드 이탈 (전량 탈출)';lines=[['TQQQ·SPYM','전량 매도'],['SGOV','대피 완료']]}else if(s.alert){name='🚨 긴급대피 발동 (TS -25%)';lines=[['TQQQ','절반 매도'],['SPYM','즉시 전환']]}else if(s.days===1){name='상단 밴드 돌파 1일 차';lines=[['TQQQ','1/3 매수'],['SGOV','일부 매도']]}else if(s.days===2){name='상단 밴드 돌파 2일 차';lines=[['TQQQ','2/3 매수'],['SGOV','추가 매도']]}else if(s.days===3){name='상단 밴드 돌파 3일 차';lines=[['TQQQ','풀매수'],['SGOV','전량 매도']]}else{name=`상단 밴드 위 ${s.days}일 차 (추세 유지)`;lines=[['TQQQ','보유 유지'],['SPYM','추가 매수']]}el.innerHTML=`<div class="signal ${s.alert?'alert':''}">${lines.map(x=>`<div class="line"><span class="token">${x[0]}</span><span>${x[1]}</span></div>`).join('')}<div>${name}</div><div>${below?'TQQQ 최고점 대비 N/A':'TQQQ 최고점 대비 '+s.dd.toFixed(1)+'%'}</div></div>`}
function chartData(closes,period,upPct,dnPct){const ma=sma(closes,period);return{p:closes.slice(-90),up:ma.slice(-90).map(v=>v==null?null:v*(1+upPct)),dn:ma.slice(-90).map(v=>v==null?null:v*(1-dnPct))}}
function renderGauge(v){const g=document.getElementById('gauge');if(!g)return;const pct=Math.max(0,Math.min(100,Number(v)));g.innerHTML=`<div class="gaugeArc"><div class="gaugeNeedle" style="transform:rotate(${(-90+pct*1.8).toFixed(1)}deg)"></div><div class="gaugeValue">${pct.toFixed(0)}</div></div><div class="gaugeScale"><span>0 극공포</span><span>50 중립</span><span>100 극탐욕</span></div>`}
async function main(){try{const d=await getMarket();document.getElementById('updated').textContent='업데이트: '+new Date(d.updated).toLocaleString('ko-KR');document.getElementById('spxPrice').textContent=fmt(d.SPX.price);document.getElementById('qqqPrice').textContent=fmt(d.QQQ.price);document.getElementById('spxDate').textContent=new Date(d.SPX.mTime*1000).toLocaleString('ko-KR');document.getElementById('qqqDate').textContent=new Date(d.QQQ.mTime*1000).toLocaleString('ko-KR');const a=chartData(d.SPX.closes,200,.025,.025),b=chartData(d.QQQ.closes,200,.02,.02);makeChart('spxChart',a.p.map((_,i)=>i),a.p,a.up,a.dn);makeChart('qqqChart',b.p.map((_,i)=>i),b.p,b.up,b.dn);renderSignal(document.getElementById('spxSignal'),d.SPX.signal);renderSignal(document.getElementById('qqqSignal'),d.QQQ.signal);const v=Number(d.FGI.value);document.getElementById('fgiValue').textContent=v.toFixed(0);document.getElementById('fgiRating').textContent=rating(v);document.getElementById('fgiAvg').textContent='30일 평균 '+Number(d.FGI.avg30).toFixed(0);renderGauge(v);charts.fgi?.destroy();charts.fgi=new Chart(document.getElementById('fgiChart'),{type:'line',data:{labels:d.FGI.history.map(x=>x.x),datasets:[{data:d.FGI.history.map(x=>x.y),borderColor:'#fff',pointRadius:2,borderWidth:1,spanGaps:true}]},options:{responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{display:false},tooltip:{mode:'index',intersect:false}},scales:{y:{min:0,max:100,ticks:{color:'#aaa'},grid:{color:'#222'}},x:{display:false}}}})}catch(e){document.getElementById('updated').textContent='API 오류: '+e.message}}
main();setInterval(main,300000);
